Modify Windows OS family types to support platform version in task definitions
aws/amazon-ecs-agent pull request #2833
Opened 2021-03-16 23:49 UTC by alxche2021

### Summary

This is currently an internal change of generating the correct Windows OS family types, which will be reflected to front end and PV support in task definitions once other changes are made.

### Implementation details

A shared API GetOSFamilyType() is defined in config package to generate Windows OS family types strings. It does not have impact on Linux by keeping its original behavior.

### Testing

Windows binary has been built for the changes. It is being tested on ECS clusters with all supported OS family types. The ECS service is running fine and the log info shows the expected Windows OS family type strings.

New tests cover the changes: No

### Description for the changelog

Feature - Modify Windows OS family types to support platform version in task definitions.

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-03-17 18:45 UTC, alxche2021 commented
I ll squash my commits into one after all tests are confirmed passing all test cases

2021-03-17 21:38 UTC, mythri-garaga commented on agent/config/parse_windows.go
> +func GetOSFamilyType() string {
Can we add unit test for this?

2021-03-17 21:41 UTC, alxche2021 commented on agent/config/parse_windows.go
> +func GetOSFamilyType() string {
Sure Mythri, I am working on it.

2021-04-16 22:02 UTC, sparrc requested changes

2021-04-16 22:02 UTC, sparrc commented on agent/config/parse_windows.go
> +		osTypeFormat = fmt.Sprintf(osTypeFormat, "2019", iType)
I find it confusing that you are defining this string as a format string (with `%s`), and then overwriting it as a regular string that ultimately gets returned.

You should create a new variable for the first part of this string similar to how you do for `iType`. In these if-statements, only set the variable to that number. As in: 
```
num := "2019"
```

then you can have just a single return like `return fmt.Sprintf("WINDOWS_SERVER_%s_%s", num, iType)`

2021-04-16 22:02 UTC, sparrc commented on agent/config/parse_windows.go
> +	releaseId, _, err := key.GetStringValue("ReleaseId")
if  i understand correctly, releaseId is only used if this is a windows server datacenter product? can you move getting of this value into that if-statement?

2021-04-16 22:02 UTC, sparrc commented on agent/config/parse_windows.go
> +	osTypeFormat := "WINDOWS_SERVER_%s_%s"
define this either as a constant in the whole package or not at all

2021-04-16 22:49 UTC, sparrc commented on agent/api/ecsclient/client.go
> +	seelog.Infof("Server OSFamily string: %s", osFamilyStr)
this seems like more of a Debugf statement

2021-04-16 22:52 UTC, sparrc commented on agent/config/parse_windows.go
> +	Windows_Server_2019       = "Windows Server 2019"
can you remove the underscores and change these to WindowsServer2019 for consistency?

2021-04-16 22:56 UTC, sparrc commented on agent/config/parse_windows.go
> +func GetOSFamilyType() string {
It seems if any step of this GetOSFamilyType function fails it seems we will just return `unknown`, should we maybe return `windows` (ie, `config.OSType`) to keep the behavior the same as before?

2021-05-12 21:58 UTC, sparrc commented
closing as this change was implemented in https://github.com/aws/amazon-ecs-agent/pull/2859

2021-05-12 21:58 UTC, closed without merging