Added support for os-family attribute to be advertised by the agent for fine grained task placement
aws/amazon-ecs-agent pull request #3044
Opened 2021-09-28 05:15 UTC by rawahars

### Summary

A new attribute is being introduced in the ECS Control plane called `ecs.os-family` which defines the os family to which the instance belongs. For Linux based instances, the OS family would be advertised as `linux` and for Windows based instances, the attribute would have a value of format - `WINDOWS_SERVER_<Windows Version>_<Installation Type>`

This would allow the customers to achieve fine grained task placement especially in a mixed cluster.

Example- If a cluster runs instances running on different Windows versions, and a task definition specifies the OS family as `WINDOWS_SERVER_2019_FULL` then this task would only be placed on the instances which broadcasted their os-family as `WINDOWS_SERVER_2019_FULL`.

### Implementation details

A new attribute has been introduced `ecs.os-family`. The values for Linux based instances is `linux`.
For Windows instances, the value can be-
`WINDOWS_SERVER_2019_FULL`, `WINDOWS_SERVER_2019_CORE`, `WINDOWS_SERVER_2016_FULL`, `WINDOWS_SERVER_2022_FULL`, `WINDOWS_SERVER_2022_CORE`, `WINDOWS_SERVER_2004_CORE`,  `WINDOWS_SERVER_20H2_CORE`

### Testing

Unit tests have been added and existing tests were updated.
Additionally, custom AMIs with custom agent built from this branch was tested to ensure that the instance can register itself to the cluster.

New tests cover the changes: 
Yes

### Description for the changelog

Added support for OS Family to the agent.
### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-09-28 18:30 UTC, fenxiong reviewed
looks good few nits

2021-09-28 18:30 UTC, fenxiong commented on agent/config/os_family_windows.go
> +func GetOperatingSystemFamily() string {
nit: can this just be GetOSFamily?

2021-09-28 18:30 UTC, fenxiong commented on agent/config/os_family_windows.go
> +	unsupportedWindowsOS = "windows"
nit: unsupportedWindowsOS -> unsupportedWindowsOSFamily

2021-09-28 18:30 UTC, fenxiong commented on agent/config/os_family_windows.go
> +	releaseIDToVersionExceptions = map[string]bool{
nit: releaseIDFromDisplayVersion sounds easier to understand

2021-09-28 21:50 UTC, jterry75 requested changes

2021-09-28 21:50 UTC, jterry75 commented on agent/config/os_family_windows.go
> +	osTypeFormat               = "WINDOWS_SERVER_%s_%s"
This is really the `osFamilyFormat` for clarity

2021-09-28 21:50 UTC, jterry75 commented on agent/config/os_family_windows.go
> +		20348: "2022",
Can we just keep these in build order? So this one should be last

2021-09-28 21:50 UTC, jterry75 commented on agent/config/os_family_windows.go
> +		seelog.Errorf("windows release with build number [%s] is unsupported", buildNumber)
`buildNumber` is an `int` so this should be `%d` or `%v` right?

2021-09-28 22:03 UTC, jterry75 approved these changes

2021-09-28 22:30 UTC, fenxiong approved these changes

2021-09-28 22:55 UTC, fierlion approved these changes
good overall test coverage!

2021-09-29 16:23 UTC, singholt commented
Just curious - What happens if a customer tries to use both os-type and os-family attributes at once, and they conflict? Example - os-type = "linux" and os-family = "windows-2019...". Do we want to add checks for such a scenario, even if it may be accidental?

2021-09-29 16:40 UTC, rawahars commented
@singholt With respect to the conflicting task placement constraints such as-

```
"placementConstraints": [
    {
      "type": "memberOf",
      "expression": "attribute:ecs.os-type == linux"
    },
   {
      "type": "memberOf",
      "expression": "attribute:ecs.os-family == WINDOWS_SERVER_2019_FULL"
    }
  ]
```

The run task call itself will fail with an error message such as `Reasons : ["MemberOf placement constraint unsatisfied.","AGENT"]. Learn more`

This is the existing behavior with any task placement constraint using the custom attribute tags. If there isn't any instance which matches both the constraints, the task would fail.

2021-09-29 16:43 UTC, singholt commented
> @singholt With respect to the conflicting task placement constraints such as-
> 
> ```
> "placementConstraints": [
>     {
>       "type": "memberOf",
>       "expression": "attribute:ecs.os-type == linux"
>     },
>    {
>       "type": "memberOf",
>       "expression": "attribute:ecs.os-family == WINDOWS_SERVER_2019_FULL"
>     }
>   ]
> ```
> 
> The run task call itself will fail with an error message such as `Reasons : ["MemberOf placement constraint unsatisfied.","AGENT"]. Learn more`
> 
> This is the existing behavior with any task placement constraint using the custom attribute tags. If there isn't any instance which matches both the constraints, the task would fail.

I agree. I'm thinking around whether we want to fail early, at register-task call?

2021-09-29 16:48 UTC, rawahars commented
ECS doesn't fail the register-task call even if we specify any random value for the task placement constraint attribute. For example, we can register a task definition with say the below placement constraint. The task would be failed during run-task.

```
"placementConstraints": [
    {
      "type": "memberOf",
      "expression": "attribute:ecs.os-type == invalidOS"
    }
  ]
```

2021-09-29 16:51 UTC, singholt commented
> ECS doesn't fail the register-task call even if we specify any random value for the task placement constraint attribute. For example, we can register a task definition with say the below placement constraint. The task would be failed during run-task.
> 
> ```
> "placementConstraints": [
>     {
>       "type": "memberOf",
>       "expression": "attribute:ecs.os-type == invalidOS"
>     }
>   ]
> ```
> 
> The same is applicable for any conflicting attributes.

thanks, makes sense

2021-09-29 17:08 UTC, merged