Add THIRD_PARTY.md attribution file to ecs-agent
aws/amazon-ecs-agent pull request #3808
Opened 2023-07-17 19:53 UTC by amogh09

### Summary

Add third party attribution file to ecs-agent module.

### Implementation details

* Added a template file `third_party.tpl` for the attribution file.
* Installed [go-licenses](https://github.com/google/go-licenses/tree/master).
* Generated `THIRD_PARTY.md` file with `go-licenses report github.com/aws/amazon-ecs-agent/ecs-agent/... --template third_party.tpl --ignore github.com/aws/amazon-ecs-agent > THIRD_PARTY.md` command.

### Testing

NA

New tests cover the changes:  no

### Description for the changelog

Add THIRD_PARTY.md attribution file to ecs-agent

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-07-17 21:00 UTC, fierlion requested changes

2023-07-17 21:00 UTC, fierlion commented on ecs-agent/third_party.tpl
> +{{ range . -}}
do we need to commit this file to code?   I used https://github.com/google/go-licenses to pull these for `/agent` and didn't commit this file there.

2023-07-17 22:21 UTC, fierlion commented on ecs-agent/third_party.tpl
> +{{ range . -}}
Update - talked offline and we'll move this into a make target workflow.  approved.

2023-07-17 22:21 UTC, fierlion approved these changes

2023-07-18 00:51 UTC, Realmonia approved these changes

2023-07-18 02:14 UTC, merged