Correct log message in UpdateTaskProtection handler.
aws/amazon-ecs-agent pull request #3861
Opened 2023-08-22 00:25 UTC by hoshank10

### Summary
 Correct log message UpdateTaskProtection handler.

### Implementation details
 Correct log message UpdateTaskProtection handler.

### Testing

New tests cover the changes: 

### Description for the changelog

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-22 16:37 UTC, amogh09 submitted a review, later dismissed

2023-08-22 17:19 UTC, xxx0624 approved these changes

2023-08-22 17:25 UTC, xxx0624 commented on ecs-agent/tmds/handlers/taskprotection/v1/handlers/handlers.go
> +		logger.Info("UpdateTaskProtection endpoint was called", logger.Fields{
Separate question - can we validate the request (line #175) earlier so that we can avoid unnecessary queries of line #161?

2023-08-22 17:44 UTC, danehlim commented
Corresponding vendored file in agent module was not updated. Did you run `go mod tidy` and `go mod vendor` in `agent/` directory?

2023-08-22 17:55 UTC, hoshank10 commented
>

2023-08-22 19:01 UTC, danehlim submitted a review, later dismissed

2023-08-22 19:57 UTC, amogh09 approved these changes

2023-08-22 23:50 UTC, Realmonia requested changes
Please change your destination branch to dev instead of master

2023-08-23 21:01 UTC, Realmonia approved these changes

2023-08-23 21:58 UTC, danehlim approved these changes

2023-08-23 22:10 UTC, merged